### ISSUE TITLE
GPX export error - stratos 3 data

### ISSUE THREAD

**Issue by rastos** [rolandsz/Mi-Fit-and-Zepp-workout-exporter#1]
I have found one issue in \gpx_file_exporter.py

when the values have for some reason empty string in the data it will throw this error

`Traceback (most recent call last):
  File "C:\temp\Mi-Fit-and-Zepp-workout-exporter\main.py", line 24, in <module>
    scraper.run()
  File "C:\temp\Mi-Fit-and-Zepp-workout-exporter\core\scraper.py", line 51, in run
    exporter.export()
  File "C:\temp\Mi-Fit-and-Zepp-workout-exporter\third_party\gpx_file_exporter.py", line 52, in export
    track_data = self.parse_track_data()
  File "C:\temp\Mi-Fit-and-Zepp-workout-exporter\third_party\gpx_file_exporter.py", line 95, in parse_track_data
    times=array.array('q', [int(val) for val in
  File "C:\temp\Mi-Fit-and-Zepp-workout-exporter\third_party\gpx_file_exporter.py", line 95, in <listcomp>
    times=array.array('q', [int(val) for val in
ValueError: invalid literal for int() with base 10: ''`

it can be easily fixed by filtering out the empty value like this on lines 95-113 in \gpx_file_exporter.py

`list(filter(None,self.data["time"].split(";")))`

**Comment by rolandsz** [comment]
Fixed in https://github.com/rolandsz/Mi-Fit-and-Zepp-workout-exporter/pull/2
