### ISSUE TITLE
New version doesn't work

### ISSUE THREAD

**Issue by k0rsakov** [rolandsz/Mi-Fit-and-Zepp-workout-exporter#11]
I run main.py as before and get the error:

```log
Traceback (most recent call last):
  File "/Mi-Fit-and-Zepp-workout-exporter/main.py", line 8, in <module>
    from src.exporters.geopandas_exporter import GeoPandasExporter
  File "/Mi-Fit-and-Zepp-workout-exporter/src/exporters/geopandas_exporter.py", line 7, in <module>
    import geopandas as gpd
  File "/Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas._config import options  # noqa
  File "/Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/geopandas/_config.py", line 109, in <module>
    default_value=_default_use_pygeos(),
  File "/Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/geopandas/_config.py", line 95, in _default_use_pygeos
    import geopandas._compat as compat
  File "/Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/geopandas/_compat.py", line 9, in <module>
    import pyproj
  File "/Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/pyproj/__init__.py", line 49, in <module>
    import pyproj.network
  File "/Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/pyproj/network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401 pylint: disable=unused-import
ImportError: dlopen(/Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/pyproj/_network.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_proj_context_is_network_enabled'
```

My pip list:
```log
Package            Version
------------------ ---------
attrs              21.4.0
black              22.3.0
certifi            2022.6.15
charset-normalizer 2.0.12
click              8.1.3
click-plugins      1.1.1
cligj              0.7.2
Fiona              1.8.21
geopandas          0.11.0
gpxpy              1.5.0
idna               3.3
isort              5.10.1
munch              2.5.0
mypy-extensions    0.4.3
nodeenv            1.7.0
numpy              1.23.1
packaging          21.3
pandas             1.4.3
pathspec           0.9.0
pip                22.1.2
platformdirs       2.5.2
pydantic           1.9.1
pyparsing          3.0.9
pyproj             3.3.1
pyright            1.1.251
python-dateutil    2.8.2
pytz               2022.1
requests           2.27.1
setuptools         57.4.0
Shapely            1.8.2
six                1.16.0
tomli              2.0.1
typing_extensions  4.3.0
urllib3            1.26.10

```

**Comment by rolandsz** [comment]
Could you please try to remove/reinstall the `pyproj` package?

**Comment by k0rsakov** [comment]
> Could you please try to remove/reinstall the `pyproj` package?

Reinstalled, doesn't work.
I also tried installing pyproj==3.3.0 and that doesn't work either

**Comment by rolandsz** [comment]
I don't think the new changes caused this issue, because according to the stack trace, it's coming from `import geopandas as gpd`, which has been already there before.

- Which Python version do you use?
- Which OS?
- Do you have the same issue when you create an empty .py file containing only `import geopandas as gpd`?

**Comment by k0rsakov** [comment]
> I don't think the new changes caused this issue, because according to the stack trace, it's coming from `import geopandas as gpd`, which has been already there before.
> * Do you have the same issue when you create an empty .py file containing only `import geopandas as gpd`?

i created a new file `test_import.py`

posted the code:
```python
import geopandas as gpd

print('hello')
```

Got this answer:
```log
Traceback (most recent call last):
  File "Mi-Fit-and-Zepp-workout-exporter/test_import.py", line 1, in <module>
    import geopandas as gpd
  File "Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas._config import options # noqa
  File "Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/geopandas/_config.py", line 109, in <module>
    default_value=_default_use_pygeos(),
  File "Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/geopandas/_config.py", line 95, in _default_use_pygeos
    import geopandas._compat as compat
  File "Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/geopandas/_compat.py", line 9, in <module>
    import pyproj
  File "Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/pyproj/__init__.py", line 49, in <module>
    import pyproj.network
  File "Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/pyproj/network.py", line 10, in <module>
    from pyproj._network import ( # noqa: F401 pylint: disable=unused-import
ImportError: dlopen(GitHub/fork/Mi-Fit-and-Zepp-workout-exporter/venv/lib/python3.9/site-packages/pyproj/_network.cpython-39-darwin .so, 0x0002): symbol not found in flat namespace '_proj_context_is_network_enabled'
```

Rewrote the code:
```python
print('hello')
```

and got the answer:
```log
hello
```

> * Which Python version do you use?

Python 3.9.7

> * Which OS?

macOS 12.4

**Comment by rolandsz** [comment]
It looks like it's a problem related to your Python environment instead of the project itself. I'm also using macOS 12.4, the only difference is the Python version - I'm using Python 3.9.13. I don't think it helps, but you could try updating it.

You may also try to recreate the `venv` from scratch.
