### ISSUE TITLE
file error 

### ISSUE THREAD

**Issue by ganq76** [rolandsz/Mi-Fit-and-Zepp-workout-exporter#18]
Thanks you to have writted this script.
 I succeeded in authentification but I have this error  :	
Traceback (most recent call last):
  File " main.py", line 72, in <module>     scraper.run()
  File "\src\scraper.py", line 41, in run     for summary in self.fetch_workout_summaries():        
  File "scraper.py", line 27, in fetch_workout_summaries     history = self.api.get_workout_history()
  File "src\api.py", line 163, in get_workout_history     model = WorkoutHistory(**response)
  File "\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 315 validation errors for WorkoutHistory
data.summary.32.strokes
  Field required [type=missing, input_value={'trackid': '1648144986',...trate_setting_type': -1}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing

I updated all the module but I have the same bug. 
Can you help me 
thanks

**Comment by rolandsz** [comment]
Thanks for the report! It should be fixed by https://github.com/rolandsz/Mi-Fit-and-Zepp-workout-exporter/commit/5b935812e739f07b39fc3784379853d6432ce1c4

**Comment by ganq76** [comment]
cool, it works ! 
thanks
